### ISSUE TITLE
how to use the code(as a gephi plugin?)

### ISSUE THREAD

**Issue by songjinghe** [tarasklas/FDEB#1]
Hei, I was look for some thing doing edge bundling and found this link:https://gephi.wordpress.com/tag/edge-bundling/
then I found your code here, but I don't know how to use the Force Direct edge bundling feature in your code. can you give some instructions?

It seem's that you fork the whole gephi repo( I see lots of gephi code here : ), must I download all of them and compile it ? or maybe you can show me which part of code is related to the feature. And I can make use of it (made it into a gephi plugin,maybe)

in the above link it said that this feature will be availabe in the next release of gephi, so how's the progress?

looking forward to your reply, thank you!

**Comment by tarasklas** [comment]
Hi,

Unfortunately it was never merged with gephi and now is very out-of-date.
You may clone this repo, containing old, but working version of gephi, and
build it with netbeans to use it(you will see new tab in view window, if I
remember correctly).
I am afraid it would not be possible to use this as a plugin, but you still
can load graphs and apply bundling with this old gephi release.

Hope this helps,
Taras

2015-07-24 9:22 GMT+03:00 songjinghe notifications@github.com:
